[package]
name = "sudoku_core"
version = "0.1.0"
authors = ["Masa Maeda <masamaedae@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12"
atty = "0.2"
